package dev.m4nd3l.loggerutil.configuration;

import java.io.File;
import java.time.format.DateTimeFormatter;

public class FileLoggerConfigurationBuilder {
    private int logFileLifeDays = 90;
    private File logDirectory = new File(System.getenv("TEMP"), "loggerutil-autogenerated");
    private DateTimeFormatter fileNameFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy-HH-mm-ss");
    private String extension = "log";

    public FileLoggerConfigurationBuilder setExtension(String extension) { this.extension = extension; return this; }
    public FileLoggerConfigurationBuilder setFileNameFormatter(String formatter) { return setFileNameFormatter(DateTimeFormatter.ofPattern(formatter)); }
    public FileLoggerConfigurationBuilder setFileNameFormatter(DateTimeFormatter fileNameFormatter) { this.fileNameFormatter = fileNameFormatter; return this; }
    public FileLoggerConfigurationBuilder setLogDirectory(File logDirectory) { this.logDirectory = logDirectory; return this; }
    public FileLoggerConfigurationBuilder setLogFileLifeDays(int logFileLifeDays) { this.logFileLifeDays = logFileLifeDays; return this; }

    public FileLoggerConfiguration create() {
        return new FileLoggerConfiguration(logDirectory, logFileLifeDays, fileNameFormatter, extension);
    }
}
