package dev.m4nd3l.loggerutil.configuration;

import java.io.File;
import java.time.format.DateTimeFormatter;

/**
 * Builder class for creating {@link FileLoggerConfiguration} instances.
 * Provides a fluent API to customize how and where log files are stored.
 */
public class FileLoggerConfigurationBuilder {
    private int logFileLifeDays = 90;
    private File logDirectory = new File(System.getenv("TEMP"), "loggerutil-autogenerated");
    private DateTimeFormatter fileNameFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy-HH-mm-ss");
    private String extension = "log";

    /**
     * Sets the file extension for the log files.
     * @param extension The extension (e.g., "log", "txt"). Default is "log".
     * @return This builder instance.
     */
    public FileLoggerConfigurationBuilder setExtension(String extension) { this.extension = extension; return this; }

    /**
     * Sets the date-time pattern used for generating log filenames.
     * @param formatter A string pattern (e.g., "yyyy-MM-dd").
     * @return This builder instance.
     */
    public FileLoggerConfigurationBuilder setFileNameFormatter(String formatter) { return setFileNameFormatter(DateTimeFormatter.ofPattern(formatter)); }

    /**
     * Sets the {@link DateTimeFormatter} used for generating log filenames.
     * @param fileNameFormatter The formatter instance.
     * @return This builder instance.
     */
    public FileLoggerConfigurationBuilder setFileNameFormatter(DateTimeFormatter fileNameFormatter) { this.fileNameFormatter = fileNameFormatter; return this; }

    /**
     * Sets the directory where log files will be saved.
     * @param logDirectory The directory as a {@link File} object.
     * @return This builder instance.
     */
    public FileLoggerConfigurationBuilder setLogDirectory(File logDirectory) { this.logDirectory = logDirectory; return this; }

    /**
     * Sets the retention period for log files.
     * @param logFileLifeDays Number of days to keep a log file before it's eligible for deletion.
     * @return This builder instance.
     */
    public FileLoggerConfigurationBuilder setLogFileLifeDays(int logFileLifeDays) { this.logFileLifeDays = logFileLifeDays; return this; }

    /**
     * Creates a new {@link FileLoggerConfiguration} with the current builder settings.
     * @return A configured configuration instance.
     */
    public FileLoggerConfiguration create() {
        return new FileLoggerConfiguration(logDirectory, logFileLifeDays, fileNameFormatter, extension);
    }
}